config/routes.rb
NoCmuWifi::Application.routes.draw do
  resources :reports, only: ['index', 'show', 'new', 'create']

  root to: 'reports#index'
end

app/models/report.rb
class Report < ActiveRecord::Base
  DEFAULT_MESSAGE = <<EOH
Advisor,

I am a student at Carnegie Mellon University.

Today, I was unable to access the Internet via the campus wireless on both CMU and CMU-SECURE.

During this time, I was unable to complete my homework, access Blackboard, collaborate with my peers, study for finals, or perform any other scholarly duties.

In the last week of classes, an outage like this is unacceptable and is directly impacting my ability to perform as a student.

Thank You
EOH

  attr_accessible :andrew_id, :location, :name, :personal

  validates_presence_of :name, :andrew_id, :location
  validates_uniqueness_of :andrew_id

  default_scope order(:location, :name)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(params[:report])

    if @report.save
      redirect_to @report, notice: 'Report was successfully created.'
      ReportMailer.go(@report).deliver
    else
      render action: 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>I can haz WiFi?</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reports/_form.html.erb
<%= bootstrap_form_for @report, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.text_field :name, :help_inline => 'e.g. Jane Parker' %>
  <%= f.text_field :andrew_id, :help_inline => 'e.g. jparker' %>
  <%= f.text_field :location, :help_inline => 'Resnik' %>
  <%= f.text_area :personal, :help_block => 'What were you working on? What class? What project? (optional)', :value => Report::DEFAULT_MESSAGE %>
  <%= f.actions %>
<% end %>

app/views/reports/index.html.erb
<%= link_to 'New Report', new_report_path, :class => 'btn btn-primary pull-right' %>
<h1>CMU WiFi Outage Reporter</h1>

<p>The CMU Networking group claims that no students report WiFi outages. As you know, there was a major outage on 12/2/12. Click "New Report" and fill out the form - we will send them an email for you.</p>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Story</th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= link_to report.name, report %></td>
    <td><%= report.location %></td>
    <td><%= truncate(report.personal, length: 200) %></td>
  </tr>
<% end %>
</table>

app/views/reports/new.html.erb
<h1>New WiFi Outage Report</h1>
<%= render 'form' %>

app/views/reports/show.html.erb
<p>
  <b>Name:</b>
  <%= @report.name %>
</p>

<p>
  <b>Location:</b>
  <%= @report.location %>
</p>

<p>
  <b>Personal:</b>
  <%= @report.personal %>
</p>